### ISSUE TITLE
[Epic] View or update your user profile

### ISSUE THREAD

**Issue by kristenshaw4** [cfpb/sbl-project#10]
#### Milestone: [Authorization](https://github.com/cfpb/sbl-project/milestone/3)
The shared data filing platform will be used by filers of small business lending (SBL) and mortgage lending (HMDA) data to centrally manage their account (user profile, financial institution profile, login through Login,gov, etc.). 

# Epic: View or update your user profile
- Once a user completes their user profile any changes to their user profile details will be handled on the "Update your user profile" page. 
- The "Complete your user profile" form is optimized for first-time users, and acts as a gate to insure the user is fully configured prior to entering the rest of the system.
- The "View your user profile" should be used to view the user profile details we have on file
- The "Update your user profile" form should be used to request updates to first name, last name, and associate an additional financial institution (MVP method TBD)
- Requested updates will be submitted to the support staff for processing (method TBD)

### Tasks
- [X] Make a list of the relevant user stories for this page
- [X] Make a list of the required content for this page
- [x] Document the work that we have done up until now including images and discussion
- [x] Surface any open questions
- [x] Review wireframes with FEWD, BEWD, Data, SBL Help, Content team members
- [x] Identify tasks for user testing (to validate findability of information, clarity of content and layout, users able to successfully complete important tasks)
- [ ] Reviewed by team for input & feedback
- [ ] User testing conducted

### MVP (Beta release)

- [x] https://github.com/cfpb/sbl-project/issues/68
- [x] https://github.com/cfpb/sbl-project/issues/69
- [x] https://github.com/cfpb/sbl-project/issues/70
- [x] https://github.com/cfpb/sbl-project/issues/71
- [x] https://github.com/cfpb/sbl-project/issues/72
 
### Backlog
- [ ] Create a post-MVP/beta issue for building the update form @sthomas93 @angelcardoz - And should we create an issue for the alternative approach we are implementing to accomplish some of the user stories listed above? 
- Update user profile email to case form. 
-  update "email our support staff" text to "update your user profile"

## Technical requirements
- Form
  - Need to connect to _case management system_ potentially with us using query parameters to pre-populate the data
- User management API
  - Reads user data from Keycloak
- Institutions API
  - Retrieve institution data by LEI and email domain

## Content requirements
A user can view:
- First name
- Last name
- Email address 
- Associated financial institutions
- Instructions on how to request to update their user profile details
- Instructions on how to update user email address via Login.gov

### Research
- Learn what users expect to happen when they update their profile information.
- Assess how easily users are able to request various changes to their profile information.
- Learn whether users expect to request changes to their profile other than the ones we currently allow.

### Task Ideation
- A user can find their profile information
- A user is able to access the update your user profile form
- A user can change their name
- A user can add one or more FI associations
- A user can remove one or more FI associations

### Updated: 2/15/2024

| View your user profile (read-only) | Update your user profile | User profile update -submission confirmation |
|------------|------------|------------|
|![Group 499](https://github.com/cfpb/sbl-project/assets/77348967/69b4ddf7-b114-4312-8788-3ea945ae2cb0)|![Group 502](https://github.com/cfpb/sbl-project/assets/77348967/63f6aa7b-541a-4e60-bfdd-d1cd691eb505)|![Group 498](https://github.com/cfpb/sbl-project/assets/77348967/d74bc8ef-d61f-4a2d-8525-a57e9a72876a)|

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @sthomas93 - I updated this issue to include the latest mock-ups for the View and Update your user profile forms. I think that when this epic was created we had one form that would serve as both View and Update. I think we need to do some work on this to make sure that we are either accounting for View and Update in this single Epic and then also update the user stories to reflect MVP. The designs I have included here assume an update form but currently the plan for MVP is not this. We should capture the MVP plan for these user stories here.

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
I changed the name to include View and update. I will do the same for the financial institution profile.
