### ISSUE TITLE
[Epic] View or update your financial institution profile

### ISSUE THREAD

**Issue by kristenshaw4** [cfpb/sbl-project#11]
### Overview
- Each financial institution/LEI will have a financial institution profile that contains the data we have on file for that financial institution. https://github.com/cfpb/sbl-project/issues/11

#### Resources
- [[Financial Institution Identifying Information (FI3) Key Points Documentation](https://github.cfpb.gov/reg-tech/fi3/wiki/Financial-Institution-Identifying-Information-(FI3)-Key-Points-Documentation)]

### Pages 

- **View financial institution profile** 
  - Read-only
- **Update your financial institution profile** form
   - User can request changes to user supplied fields (RSSD ID, Type of financial institution, Parent and Top holder information)
   - Any changes to non-user supplied data should be handled at the source (GLEIF, NIC, etc.)
   - To request an update a user will fill out and submit a form to our support staff for processing. 
   - Form is hosted on Small business lending platform and output is delivered to the _case management system_ (email to case) https://github.com/cfpb/sbl-project/issues/82#issuecomment-1946983564

### Tasks
- [x] Pull together initial list of relevant user stories for this epic
- [x] Make a list of the content requirements for this epic
- [x] Make a list of the technical requirements for this epic
- [x] Post current wireframes and mock-ups
- [x] Review wireframes and mock-ups with FEWD, BEWD, Data, SBL Help, Content team members
- [ ] Refine user stories to prepare for development phase
- [ ] Identify and capture tasks for user testing
- [ ] Conduct user testing

### MVP (release date: 12/31/2024)
- [ ] https://github.com/cfpb/sbl-project/issues/267

### Open beta (released 8/1/2024) 
- [x] #37 
- [x] #38 
- [x] https://github.com/cfpb/sbl-project/issues/82
- [x] #37 

### Backlog
- [ ] #39 
- [ ] Alert user  if they don't have an active LEI, or if they are missing their TIN or Type of financial institution data they'll be blocked from submission.

## Technical requirements
- Institutions API
  - Retrieve institution data by LEI and email domain

## Content requirements
- Provide users with information about CFPB data sources for context and awareness
- Provide users with instructions for updating their FI's data
- FI data (see below) 

#### Financial Institution data to show on this page (in this order):
- Financial institution name 
- LEI (LEI is primary key, and name is recognizable to user)
- LEI status
- Headquarters address
- Email domain(s)
- Tax ID
- RSSD ID
- Federal prudential regulator
- Type of financial institution (SBL - MVP)
    - Financial Institution type (HMDA - future state)
- Affiliate
    - Parent Entity
        - Parent Entity Name
        - Parent Entity LEI
        - Parent Entity RSSD ID
    - Top Holder
        - Top Holder Name
        - Top Holder LEI
        - Top Holder RSSD ID
- Change History (post-MVP)

### Research Goals
- Learn what users expect to happen when they update the information for their financial institution.
- Assess how easily users are able to request various changes to their financial institution's information.
- Learn whether users expect to request changes to financial institution details other than the ones we currently allow.
- Understand what users expectations are around data that is pulled in from other sources (GLEIF, NIC).
- Identify any confusion around whether certain fields are applicable and how to obtain and format that information.

### Task Ideation
- A user can find the financial institution details page
- A user is able to access the form to update financial institution details
- A user can request changes to identifying information and affiliate information
- A user understands how to change information that's pulled in from an external database

### Updated: 2/16/2024

| View | View (LEI inactive) | 
|------------|------------|
|![Group 571](https://github.com/cfpb/sbl-project/assets/77348967/51832d5d-4cec-4938-b598-3f16f10241fe)|![Group 572](https://github.com/cfpb/sbl-project/assets/77348967/f6a3e327-bcd3-43f1-9340-10d1c88e0f3f)|

| Update | Successful submission |
|------------|------------|
|![Group 575](https://github.com/cfpb/sbl-project/assets/77348967/c3d1659e-de48-4d5a-be70-c44a8d139d9c)|![Group 574](https://github.com/cfpb/sbl-project/assets/77348967/44bd8580-3d2d-4a45-bc9c-bd4c01d8744a)|

### Financial institution data points

Field name | User can edit in platform | User can note/flag changes to historical data | Possible field contents | Source | Note 
-- | -- | -- | -- | -- | -- 
Financial institution name | No  | Yes  | Populated or "Not available"  | Always pulled from GLEIF | 
Headquarter's address | No | Yes  | Populated or "Not available" | Always pulled from GLEIF |
Legal Entity Identifier (LEI) | No |  ? | Populated or "Not available"? | Always pulled from GLEIF | 
Legal Entity Identifier Status | No |  N/A | Issued or Lapsed | Always pulled from GLEIF |  
Research, Statistics, Supervision, Discount Identification (RSSD ID) number | No | Yes | Populated or "Not applicable"? | Always pulled from NIC | 
Federal Taxpayer Identification Number (TIN) | Yes (conditional) | Yes | Populated or "Not available"? (or would this one be blank?) | NIC or User supplied (mainly non-depositories) | Supplied by user if absent from NIC. Not all institutions are listed in NIC, so many (non-depositories) will need to provide. | 
Federal prudential regulator | No | Yes? | Populated or "Not available" | Always pulled from NIC |
Type of Financial Institution | Yes (all filers) | No, because it can be directly edited in the platform  | Populated or blank (or "Not available") | Platform (profile and sometimes in the filing flow (if not previously provided) |
Parent Name | Yes (conditional) | Yes? | Name or "Not applicable" | GLEIF, NIC, or user supplied (conditional) | Supplied by user if absent from NIC/GLEIF | 
Parent LEI | Yes (conditional) | Yes? | Populated or "Not available" | GLEIF or user supplied (conditional) | Supplied by user if FI has a reporting exception in GLEIF that prevents the top holder from being linked but does in fact have a top holder with an LEI. | 
Parent RSSD ID | Yes (conditional) |  Yes? | Populated or "Not available" | GLEIF or user supplied (conditional) | Supplied by user if FI is absent from NIC but FI's parent is in NIC | 
Top Holder Name | Yes (conditional) | Yes? | Populated or "Not applicable" | GLEIF or user supplied (conditional) | Some institutions will have top holders that are not listed in either NIC or GLEIF. Supplied by user if absent from NIC/GLEIF. |
Top Holder LEI |  Yes (conditional) | Yes? | Populated or "Not available" | GLEIF or user supplied (conditional) |  Supplied   by user if FI has a reporting exception in GLEIF that prevents the top holder from being linked but does in fact have a top holder with an LEI | 
Top Holder RSSD ID | Yes (conditional) | Yes? | Populated or "Not available" | GLEIF or user supplied (conditional) | Supplied by user if FI is absent from NIC but FI's top holder is in NIC | 

### Filing specific data points
Field name | User can edit in platform | User can note/flag changes to historical data | Possible field contents | Source | Note 
-- | -- | -- | -- | -- | -- 
Voluntary reporter status | Yes (all filers) | No, because it can be directly edited in the platform | Voluntary reporter or Not a voluntary reporter | Platform (filing flow) |
Point of contact | Yes (all filers) | No, because it can be directly edited in the filing flow | All required content is populated | Platform (filing flow) |

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 

## Decision
Last week the team discussed the question of conditional logic for the "Update your financial institution profile" form. The team determined that the logic around when or what should be editable (for the identifying and affiliate sections) is too complicated for MVP. 

### For MVP: 
- In the "Identifying information" section Federal Taxpayer Identification Number (TIN) and Research, Statistics, Supervision, Discount (RSSD) ID will be editable
- All fields in the "Affiliate" section will be editable.    

### Post-MVP: 
We created a task to capture this work which will be picked up post-MVP: https://github.com/cfpb/sbl-frontend/issues/248

These notes were pulled from the design comments and will inform the post-MVP task: 
- If (and only if) RSSD ID AND LEI are empty (not in the database) then the name field should be available
- RSSD and LEI should never be editable for now
- IF we have an LEI or RSSD ID, then the name should be disabled (and hopefully populated), the LEI and RSSD data should also be disabled

@Kibrael @nongarak @billhimmelsbach
