### ISSUE TITLE
[Story] Certify filing data and sign and submit

### ISSUE THREAD

**Issue by sthomas93** [cfpb/sbl-project#113]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [[Epic] Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story

As an authorized representative of my financial institution, I want to certify the accuracy and completeness of the data reported, and sign and submit my filing, so that I can finalize my submission.

### Acceptance criteria

- Given an authorized representative of the financial institution has reviewed every section of the sign and submit page and confirmed that the information is correct,  when they scroll to the end of the page they'll be able to certify the accuracy and completeness of the data reported by providing an electronic signature, then they'll be able to submit their filing. 

### Tasks

Team members should create tasks and add links (below) prior to sprint planning.

#### UX
- [x] Write initial user story
- [x] Validate user story with the team
  - Review against task analysis for accuracy and relevance
  - Review for specificity and completeness
- [x] https://github.com/cfpb/sbl-ux/issues/15
- [ ] https://github.com/orgs/cfpb/projects/21/views/6?pane=issue&itemId=85426637&issue=cfpb%7Csbl-ux%7C21

#### Front end
- [x] https://github.com/cfpb/sbl-frontend/issues/1008

#### Back end
- [ ] Task (link)
