### ISSUE TITLE
[Epic] Complete your user profile (first time user)

### ISSUE THREAD

**Issue by kristenshaw4** [cfpb/sbl-project#12]
#### Milestone: [Authorize](https://github.com/cfpb/sbl-project/milestone/3)
The shared data filing platform will be used by filers of small business lending (SBL) and mortgage lending (HMDA) data to centrally manage their account (user profile, financial institution details, login through Login,gov, etc.). 

# Epic: Complete your user profile (first time user)
### Overview 
- The user will arrive at this page on their first visit after creating their Login.gov account and/or logging in with Login.gov
- This screen will act as a gate to insure the user is fully configured prior to entering the rest of the system.
- Once the user has a user profile and is authorized they will not see this page again. 
- For an authorized user any changes to their user profile will be handled on the "Request changes to your user profile" page. 

#### Steps:     
- The user logs in through Login.gov and lands on this page
- The user will be asked to enter their First name and Last name 
- Their email address will auto-populate based on the email address they used to sign in with Login.gov. 
- They will be able to associate with one or more financial institutions either by selecting from a pre-populated list of financial institutions/LEIs OR by filling out and submitting the Salesforce form. 
- Only the selections from the pre-populated list of financial institutions/LEIs that match their email domain will allow a user immediate access to the system.
- Submissions via the Salesforce form will be handled by the support staff (SBL help). 

### Tasks
- [x] Pull together the relevant user stories for this epic
- [X] Make a list of the content requirements for this epic
- [X] Make a list of the technical requirements for this epic
- [X] Post current wireframes and mock-ups
- [x] Review wireframes and mock-ups with FEWD, BEWD, Data, SBL Help, Content team members
- [x] Refine user stories to prepare for development phase
- [x] Identify tasks for user testing (to validate findability of information, clarity of content and layout, users able to successfully complete important tasks)

### Prioritized for MVP:
- [x] #17
- [x] #18
- [x] #19 
- [x] #23
- [x] #27
- [x] #62

### Backlog
- [ ] #22 
- Given a user's financial institution email address does not match any of our approved email domains and their application for an LEI is in process with GLEIF, when the user tries to complete their user profile, then they will be redirected to the **Update your user profile** (Salesforce form) and will be alerted that their profile may take longer to complete while GLEIF processes their application. 
 
## Technical requirements
1. User management API
    1. Reads data from and writes data back to Keycloak
1. Institutions API
    1. Retrieve institution data by LEI and email domain
    
#### Scenario 1: The user sees all of the financial institutions they are authorized to file for
- What do users expect the system to do to verify that they should be associated with an institution?
- How much do users trust our system to correctly associate individuals with institutions?
- Do users understand how to get additional help?

#### Scenario 2: The user does not see all of the financial institutions they are authorized to file for
- What does the user expect to do so that they can be associated with their institution(s)?
- Do users understand each piece of information we are asking them to provide?
- What do users expect to happen after submitting this information?

#### Scenario 3: User logs in to Login.gov using a personal email address
- Does the user understand what went wrong?
- Does the user know what to do next?

### Updated: 12/28/2023

Scenarios for financial institution association/email domain/email address

## Scenario 1: The user sees all of the financial institutions they are authorized to file for
- User logs in through Login.gov with their financial institution’s email address.
- Front end calls the back end to check for personal email address. This passes. 
- The front end calls the back end to see if there are any matches between the user’s email domain and a financial institution email domain in our financial institution database.
- The user's email domain matches the email domain of a financial institution in our financial institution database
- The back end returns the list of matches and the front end presents those matches to the user. 
- The user sees a list of one or more matches and selects the financial institution(s) that they are authorized to file for by clicking the checkbox. 
- If the user does not see the financial institution that they are authorized to file for in the list they click on the "Contact support staff" link.
- The user clicks submit to submit their first name, last name, and financial institution.
- On the back end Keycloak gets updated with the user’s first name, and last name, and the user is added to the Keycloak group (the institution)
- The user advances to the shared landing page (authenticated).  

| Scenario 1 |
|------------|
|![Scenario 1_ Financial institution and associated email domain is in our database](https://github.com/cfpb/sbl-project/assets/77348967/2d7b49bf-8439-4414-98d0-0e8ec0ab5511)|

## Scenario 2: The user does not see all of the financial institutions they are authorized to file for
 
- User logs in with their financial institution email address. 
- Front end calls the back end to check for personal email address. This passes. 
- The front end calls the back end to see if there are any matches between the user’s email domain and a financial institution email domain in our financial institution database. 
- On the back end the user’s email domain does not match the email domain of a financial institution in our database. The backend does not return any matches. 
- The front end displays a Salesforce form. 
- The user fills out the Salesforce form and submits to the support staff.
- The support staff receives the form output via email.
- [See specific help process - by the end of this process the user's email domain has been associated with the financial institution and their user profile is complete. 
- The user receives an email from the help team which includes a link to the shared landing unauthenticated page. 
- The user clicks the log in link, logs in with Login.gov, and advances directly to the shared landing (authenticated) page. 

| Salesforce form | Salesforce notification |  
|------------| ------------|
|![Scenario 2_ Complete your user profile (Salesforce form)](https://github.com/cfpb/sbl-project/assets/77348967/dab5ac32-db78-4cc5-bf4c-ad4a4a95b72a)|![Scenario 2_ Complete your user profile details - submission confirmation (Salesforce form)](https://github.com/cfpb/sbl-project/assets/77348967/2d158257-bddb-4f9c-af42-318dd9064a99)|

## Scenario 3: User logs in to Login.gov using a personal email address
- User logs in to Login.gov using their personal email address
- On the back end the user’s email address is checked against the deny list and matches one of the denied email domains. 
- User sees a notification message indicating that they must log in again using their financial institutions email address. 
- User returns to Login.gov and logs in with their financial institution email address.  

| User logs in with personal email address |
|------------|
|![Scenario 3_ User logs in with personal email address and is denied](https://github.com/cfpb/sbl-project/assets/77348967/a26e72c5-dc77-4fa9-9c53-8490af057db4)|

### Scenario 4: User submits form without filling out all the required fields 

| User submits incomplete form |
|------------|
|![Scenario 4_ Form feedback when required fields are not filled out](https://github.com/cfpb/sbl-project/assets/77348967/42b936bd-4353-4daa-820b-fa91dda0e155)|

**Comment by dan-padgett** [comment]
@angelcardoz User testing section has been updated and the relevant checklist item has been marked complete.
