### ISSUE TITLE
[Epic] Small business lending filing home

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-project#14]
#### Milestone: [View financial institution details](https://github.com/cfpb/sbl-project/milestone/2)
The small business lending filing app will be used by financial institutions to file their annual lending data, view past filings, view financial institution details for past filings and review data files for errors and warnings. 

# Epic: Small business lending filing home

### Overview
The small business lending filing home is the starting point for filing small business lending data.

### Tasks
- [X] Make a list of the parts of the SBL filing home (based on HMDA filing home)
- [X] Document any remaining filing home SBL components that have not been discussed in other issues
- [X] Create a sketch of the full page
- [x] Identify and capture tasks for user testing
- [ ] Conduct user testing

### MVP (Beta release)
- [ ] https://github.com/cfpb/sbl-project/issues/77
- [ ] https://github.com/cfpb/sbl-project/issues/120
- [ ] https://github.com/cfpb/sbl-project/issues/121
- [ ] https://github.com/cfpb/sbl-project/issues/123
- [ ] https://github.com/cfpb/sbl-project/issues/127

### Backlog (post-MVP)
- [ ] https://github.com/cfpb/sbl-project/issues/107
- [ ] https://github.com/cfpb/sbl-project/issues/122
- [ ] As a filer, I can see a list of inactive institutions I have filed for in the past.
- [ ] As a filer, I can view the institution data snapshot for a past filing season.
- [ ] As a filer, I can view the actions I have taken for a given filing period
- [ ] As a filer, I want to be able to select the desired filing period from a dropdown of filing period years.

### Questions
1. How much consideration do we need to give now to all of the 2nd year+ scenarios?
    1. A filer is told by SEFL they need to re-file after an exam.
    1. A filer didn't file for a past year.
1. Are we going to have a 3-year window where we allow refiling like HMDA?

### Technical requirements
- List item
- List item

### Content
- Comprehensive instructions on the steps of the filing process. 
- Restart the filing process for a filing that was previously submitted

### Research goals
- Learn whether users understand where they are in the filing process for each financial institution
- Identify difficulties and barriers to getting started with filing and submitting a filing on time
- Learn what users expect the first step of the filing process to be

### Task ideation 
- Start the filing process for a given institution
- Continue the filing process for a given instituion
- Review financial institution details

#### Updated: MM/DD/YYYY

The purpose of this mock-up is to give an impression of how the components that I have shared might fit together. The details are all subject to change based on the design and functionality of the rest of the filing platform screens.

| SBL filing home | 
|------------|
|![9ec867c2-f0cf-4ad7-8885-f3d6afb53674](https://github.com/cfpb/sbl-project/assets/77348967/69d4f3d6-8584-4d28-a936-e8d19b66dd47)|

**Comment by dan-padgett** [comment]
@angelcardoz @natalia-fitzgerald three last questions for the task flow related to how we handle progress:
1. If a filing has been submitted, what actions can the user take? Currently we will show them that the filing is submitted. But should they be able to review the submission?
2. When it comes to showing progress for the filing process, one approach is to include the date that a page was last accessed or updated (or, a bit more user friendly, whether it's been updated since they last viewed the page). To me, this seems like a good way to go for steps like reviewing financial institution details where there's not as clear of a linear flow like there is for the file upload step. For the file upload step we would still include the progress indicator. What do you think of this proposal?
3. I've modified the task flow so that what the user sees on this page depends on what they've done:
   - If they haven't started, they only have a way to start the process
   - If they've started the process but haven't completed the file upload step, they see all the steps except the final one
   - Once their file is error free, they see the final step

The thought behind this approach is that it's another way to indicate progress: as you complete more steps, you have more actions available to you. Do you think this approach is worth pursuing?

**Comment by natalia-fitzgerald** [comment]
@dan-padgett 
I have some additional questions that are a little jumbled together (definitely broader than this epic) but hopefully some useful morsels in here. 

## Questions for discussion

What does a user gain in knowing that a step is in progress but not completed? If in progress simply means that any change was made (box checked, file uploaded, text input populated) wouldn't a user need to know _what_ change was made for this progress status information to be useful? If they know something was done but don't know _what_ then don't they have to review everything again anyway? 

Zooming out a little further if a user can revisit any step in the filing process (or even if they can't) then no step is really ever complete until the filing is signed and submitted. The filing is in progress in all respects until the submit filing button is clicked. So when we say _completed_ for a step or task what do we mean and what does this mean to a user?

Can a user come back and resubmit (changing whatever they wish) as many times as they wish until the filing deadline is reached or until a certain period is reached (3 years for HMDA?)?

Is the "Review financial institution details" step (which doesn't fit in the sequential flow) the one that is leading us to the need for prioritizing the visualization of the status of each step in the process on the homepage? If the steps were sequential would we still need this?  

What does a user lose if they only see the current status more broadly (not started, in progress, complete) and they return to the next step (in other words the step which they have not yet clicked the save and continue for). If there is a need to allow them to jump around in the flow? If yes, an alternative to explore is giving them a way to do this _within the filing process_ instead of from the filing home.

If "Review financial institution details" is outside of the sequential steps should we consider separating it out from the sequential steps/the filing flow without sacrificing the rest of the sequential flow? Maybe we could include a link on the financial institution card. And then we could include a review FI step (read-only) at the end of the filing process as a part of provide financial institution point of contact and sign and submit. Just brainstorming.

Or we can leave the review/update at the beginning and also put it at the end. So it doesn't stop the user from proceeding but it gets them to start thinking that they will need these details to be accurate before they file. At the end it could be an actual confirmation of the financial institution details (read-only) they are about to submit with their filing. 

Speaking of which, what language do we need to communicate that the financial institution details must be accurate to file? Thus far there is no language to this effect in what we've built/are building. As a part of the "Review fi details" step we'll want to provide context as to why this content needs to be accurate. 

What happens if the financial institution profile details (in our system) change before the filing deadline (either because of user requests OR because of data source updates)? Does the user's filing get updated with whatever is current in our system on the filing deadline date or does the information only reflect the financial institution details as true on the date of submission?

**Comment by angelcardoz** [comment]
Reorganized epic content to match new epic template.
