### ISSUE TITLE
[Epic] Provide type of financial institution

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#143]
**Milestone:** [Link to milestone]
Add a few sentences to describe the milestone.

# Epic: Provide type of financial institution

### Overview

- A financial institution complies with § 1002.109(b)(9) by selecting the applicable type or types of financial institution from the list below. A financial institution shall select all applicable types.
  - Bank or savings association
  - Minority depository institution
  - Credit union
  - Nondepository institution
  - Community development financial institution (CDFI)
  - Other nonprofit financial institution
  - Farm Credit System institution
  - Government lender
  - Commercial finance company
  - Equipment finance company
  - Industrial loan company
  - Online lender
  - Other
- Type of financial institution submissions do not go to support staff for processing.

### Tasks

Use the following checklist to ensure each epic is built out properly. If needed, you can add or remove items.
- [ ] Pull together initial list of relevant user stories for this epic
- [ ] Make a list of the content requirements for this epic
- [ ] Make a list of the technical requirements for this epic
- [ ] Post current wireframes and mock-ups
- [ ] Review wireframes and mock-ups with FEWD, BEWD, Data, SBL Help, Content team members
- [ ] Refine user stories to prepare for development phase
- [ ] Identify and capture tasks for user testing
- [ ] Conduct user testing

### MVP (Beta release)
- [ ] https://github.com/cfpb/sbl-project/issues/139

### Backlog (post-MVP)
- Story (link)

### Technical
- List item
- List item

### Content
- Link item
- Link item

### Research goals
- Add here

### Task ideation
- Add here

#### Updated: MM/DD/YYYY

| Page name | Page name | Page name |
|------------|------------|------------|
|![Image](Link)|![Image](Link)|![Image](Link)|
