### ISSUE TITLE
[Epic] Confirm financial institution details

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-project#15]
#### Milestone: [View financial institution details](https://github.com/cfpb/sbl-project/milestone/2)

# Epic: Confirm financial institution details

### Overview
- This is one way SBL is different from HMDA. HMDA has the "Transmittal Sheet" as
   the first record of their file, which contains their institution data for a given
   filing season. So, we can't really "do what HMDA does" for this one.
- Are there institution data fields that the user can fix themselves?
    1. Can they do it on this screen, or do they go back to the **View financial institution details**page in the shared data filing platform?
- Does a user have to go through this screen every time they upload a new version?
    1. Seems like the answer should be _no_, but then how does the flow work?

### Tasks
- [ ] Make a list of the relevant user stories for this epic
- [ ] Make a list of the content requirements for this epic
- [ ] Make a list of the technical requirements for this epic
- [ ] Document the work that we have done up until now including images and discussion
- [ ] Surface any open questions
- [ ] Identify tasks for user testing (to validate findability of information, clarity of content and layout, users able to successfully complete important tasks)
- [ ] Reviewed by team for input & feedback
- [ ] Conduct user testing

### MVP (Beta release)
- [x] https://github.com/cfpb/sbl-project/issues/139
- [ ] https://github.com/cfpb/sbl-project/issues/140
- [ ] https://github.com/cfpb/sbl-project/issues/141
- [ ] https://github.com/cfpb/sbl-project/issues/142

### Backlog (post-MVP)
- Story (link)

### Technical
- List item
- List item

### Content
- Link item
- Link item

### Research goals
- Add here

### Task ideation 
- Add here

#### Updated: MM/DD/YYYY

| Page name | Page name | Page name |
|------------|------------|------------|
|![Image](Link)|![Image](Link)|![Image](Link)|

**Comment by angelcardoz** [comment]
Reorganized epic content to match new epic template.

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
We should go over this epic at some point to see if it is still relevant in the current framework. We have an epic for View/Update.
