### ISSUE TITLE
[Epic] Provide point of contact

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#150]
**Milestone:** [Link to milestone]
Add a few sentences to describe the milestone.

# Epic: Provide point of contact

### Overview

- Regulations B requires financial institutions to report the name and business contact information of a person who may be contacted with questions about the financial institution’s submission
- List item

### Tasks

Use the following checklist to ensure each epic is built out properly. If needed, you can add or remove items.
- [ ] Pull together initial list of relevant user stories for this epic
- [ ] Make a list of the content requirements for this epic
- [ ] Make a list of the technical requirements for this epic
- [ ] Post current wireframes and mock-ups
- [ ] Review wireframes and mock-ups with FEWD, BEWD, Data, SBL Help, Content team members
- [ ] Refine user stories to prepare for development phase
- [ ] Identify and capture tasks for user testing
- [ ] Conduct user testing

### MVP (Beta release)
- [ ] https://github.com/cfpb/sbl-project/issues/147
- [ ] https://github.com/cfpb/sbl-project/issues/148
- [ ] https://github.com/cfpb/sbl-project/issues/149

### Backlog (post-MVP)
- Story (link)

### Technical
- List item
- List item

### Content
- Link item
- Link item

### Research goals
- Add here

### Task ideation
- Add here

#### Updated: MM/DD/YYYY

| Page name | Page name | Page name |
|------------|------------|------------|
|![Image](Link)|![Image](Link)|![Image](Link)|

**Comment by nongarak** [comment]
I just confirmed with Tim Lambert of OFLEO, and pending any revisions from someone else in the office who is on vacation, the fields that we should capture are the same as HMDA. Name, email, phone, and business address.

**Comment by nongarak** [comment]
I don't know what validations are in place for HMDA on phone number, but if it's possible to standardize phone number input in the field that would be a good thing probably. Like, 10 digits only, or requiring +1, or +1 (xxx) xxx-xxxx, or whatever other standard we want. I don't care, but probably locking it down is good. Especially so folks don't put in "nunya" or something.

**Comment by natalia-fitzgerald** [comment]
@nongarak 
Here's what I pulled from HMDA (filing instructions guide): 

"Enter the name, telephone number, e-mail address, and office address of a person who may be contacted with questions about your institution's submission."

**Enter the contact person's:**
1. Name
2. Telephone Number
3. E-mail Address
4. Address
a. Street Address 
b. City
c. State
d. ZIP Code

**Formatting specifications**
1. Full Name as (1) data field
2. Telephone Number (Format: 999-999-9999)
3. E-mail Address
4. Address
  a. Street Address as (1) data field 
  b. City as (1) data field
  c. State (two-letter state code as (1) data field 
  d. ZIP Code as (1) data field 
  
@billhimmelsbach - What other field formatting can we do for these types of fields? We can provide formatting examples in the fields but I'd like to identify what's possible for the front end to do as well. If we want the full name to ultimately be one data field do we have to only show one text input field "Full name" or can we show "First name" and "Last name" and have these be merged as one data field on our end? Preference?   

@nongarak 
- HMDA says that phone number should be formatted as follows: 999-999-9999. Is this what we want to use for SBL? 
- What US territories should be included, in addition to the states?

**Comment by hkeeler** [comment]
As for the **State** field, I'm guessing we'd want to go with the same values we allow for institution records. On https://github.com/cfpb/regtech-user-fi-management/issues/48#issuecomment-1805194291 we said...

>Values here should be pretty self-explanatory. All 50 states **_and_** D.C. and  territories...
>
>code | name
>---|---
>`AS` | American Samoa
>`DC` | District of Columbia
>`GU` | Guam
>`MP` | Northern Mariana Islands
>`PR` | Puerto Rico
>`UM` | United States Minor Outlying Islands
>`VI ` | Virgin Islands, U.S.
>
>...assuming we're going with [ISO-3166](https://en.wikipedia.org/wiki/ISO_3166-2:US#Subdivisions_included_in_ISO_3166-1).

Pretty sure we decided to go with that.
