### ISSUE TITLE
[Epic] Resolve Errors

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#166]
**Milestone:** [Resolve errors](https://github.com/cfpb/sbl-project/milestone/6)

# Epic: Resolve Errors

### Overview

- The Resolve errors page is the place where a user can look at all data errors for their uploaded file. The system will indicate what the errors are, where the errors are, and what they need to do about errors. The system will also allow the user to download a version of the validation report.
- A covered financial institution shall compile and maintain data regarding covered applications from small businesses. The data shall be compiled in the manner prescribed in [12 CFR § 1002.107](https://www.consumerfinance.gov/rules-policy/regulations/1002/107/)  and the [Filing Instructions Guide](https://www.consumerfinance.gov/data-research/small-business-lending/filing-instructions-guide/2024-guide/) for the appropriate year. The data compiled shall include the items described in paragraphs (a)(1) through (20) of this12 CFR § 1002.107 .
- List item

### Tasks

Use the following checklist to ensure each epic is built out properly. If needed, you can add or remove items.
- [ ] Pull together initial list of relevant user stories for this epic
- [ ] Make a list of the content requirements for this epic
- [ ] Make a list of the technical requirements for this epic
- [ ] Post current wireframes and mock-ups
- [ ] Review wireframes and mock-ups with FEWD, BEWD, Data, SBL Help, Content team members
- [ ] Refine user stories to prepare for development phase
- [ ] Identify and capture tasks for user testing
- [ ] Conduct user testing

### MVP (Beta release)
- [ ] https://github.com/cfpb/sbl-project/issues/111
- [ ] https://github.com/cfpb/sbl-project/issues/108

### Backlog (post-MVP)
- Story (link)

### Technical
- List item
- List item

### Content
- Link item
- Link item

### Research goals
- Add here

### Task ideation
- Add here

#### Updated: MM/DD/YYYY

| Page name | Page name | Page name |
|------------|------------|------------|
|![Image](Link)|![Image](Link)|![Image](Link)|
