### ISSUE TITLE
[Story] Complete user profile (first name + last name) upon first login

### ISSUE THREAD

**Issue by hkeeler** [cfpb/sbl-project#17]
### User story

As a filer, I would like to complete my user profile (first name + last name) upon my first login, so that I can begin the filing process.

### Acceptance criteria

- [x] Given a user has authenticated with Login.gov, when they access RegTech Home for the first time, then they should be routed to the **Complete your user profile** page displaying the email address used to login with.
- [x] Given a user is filling out the **Complete your user profile** form, when they have filled in all required fields (**First name** and **Last name**), then the **Submit** button will become active

### Depends on

- #12

#### Complete User Profile Layout
- [x] [User Profile - Layout View - Initial User Profile Form](https://github.com/cfpb/sbl-frontend/issues/26)
- [x] [User Profile - Initial User Profile Form - Validation Fail State (User Input Error Messages)](https://github.com/cfpb/sbl-frontend/issues/29)
- [x] [User Profile - Layout View - Fetch User's Related Financial Institution Data](https://github.com/cfpb/sbl-frontend/issues/40)
- [x] [User Profile - Layout View - Select Dropdowns for Financial Institutions](https://github.com/cfpb/sbl-frontend/issues/41)
- [x] [User Profile - Layout View - Associated Financial Institutions Input Elements](https://github.com/cfpb/sbl-frontend/issues/58)
- [x] [User Profile -  Layout View - Submitted User Profile - Successful](https://github.com/cfpb/sbl-frontend/issues/42)
- [x] [User Profile -  Layout View - Submitted User Profile - Failed](https://github.com/cfpb/sbl-frontend/issues/43)
- [x] [User Profile - Update the User Profile layout based on the MVP discussion](https://github.com/cfpb/sbl-frontend/issues/75)
- [x] [User Profile - Salesforce Variant](https://github.com/cfpb/sbl-frontend/issues/82)
- [ ] User Profile - Initial User Profile Form - Timeout or 401/500 Error Messages
- [ ] User Profile - Initial User Profile Form - Add Accessibility
- [ ] User Profile - Initial User Profile Form - Add unit and e2e tests
#### View/Update Your User Profile
- [x] [View your User Profile](https://github.com/cfpb/sbl-frontend/issues/86)
- [x] [Update your User Profile](https://github.com/cfpb/sbl-frontend/issues/87)
#### User Profile Data
- [x] [User Profile - Frontend Validation schema for user input (e.g. `First name is required`). - Draft](https://github.com/cfpb/sbl-frontend/issues/28)
- [ ] User Profile - Backend Validation schema for receiving the user input and LEI data. - Draft
- [ ] User Profile - Routing-Force the user to create a `User Profile` before having access to the rest of the app.
- [x] [User Profile - REST API to combine user profile and user fi association request.](https://github.com/cfpb/regtech-user-fi-management/issues/11)
- [x] [User Profile - Create **Complete your user profile** form page.](https://github.com/cfpb/sbl-frontend/issues/1)
- [ ] User Profile - Create **User profile submission status** page for successful submission. 
- [ ] User Profile - Create error section for the **User profile submission status** page on failed submission.
- [ ] User Profile - ~~Retrieve institutions by search query (i.e. text search)~~ Retrieve institution by LEI only
