### ISSUE TITLE
[Story] Receive on-screen confirmation of successful submission

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#183]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story

- As a filer, I want to receive an on-screen confirmation that I've successfully submitted by filing, so I know the process is complete. 

### Acceptance criteria

- Given a filer has signed and certified their filing, when they click on the "Submit filing" button, then they will see an alert that includes: 
  - Name of the person that submitted the filing
  - Confirmation number for the filing
  - Date and time that the filing was submitted

### Tasks

Team members should create tasks and add links (below) prior to sprint planning.

#### UX
- [x] Write initial user story
  - Review against task analysis for accuracy and relevance
  - Add link to story from task analysis
- [x] Validate user story with the team
  - Review for specificity and completeness
- [x] https://github.com/cfpb/sbl-ux/issues/15

#### Front end
- [x] https://github.com/cfpb/sbl-frontend/issues/1008

#### Back end
- Task (link)

**Comment by angelcardoz** [comment]
Changed from "As a filer, I want to receive on-screen confirmation that the beta filing flow has ended, so that I know the filing process is complete." to "As a filer, I want to receive an on-screen confirmation that I've successfully submitted by filing, so I know the process is complete. "

**Comment by natalia-fitzgerald** [comment]
The filing confirmation alert is now live on beta. The following screenshots show some information that was implemented as a part of a different story but I'm including these here as a visual confirmation of the completion of this story. 

### Beta version
<img width="925" alt="Screenshot 2024-12-11 at 11 59 44 AM" src="https://github.com/user-attachments/assets/d919bb23-b174-42d6-b1b0-ec841da1a606" />

### Production version
<img width="526" alt="Screenshot 2024-12-11 at 12 02 19 PM" src="https://github.com/user-attachments/assets/f4ca77ad-e749-43df-91a3-3e252fe0065d" />

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
This feature has now been implemented on beta. This story is completed and can be closed.
