### ISSUE TITLE
[Story] Receive email confirmation of successful submission

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#184]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story
- As a filer, I want to receive email confirmation that my submission was successful, so that I know the filing process is complete.

### Acceptance criteria

- [x] Given a user is on sign and submit, when they submit their filing, then they receive an email confirmation that includes the information included in the on-page confirmation alert.
- [x] Given a user is on sign and submit in the beta environment, when they submit their filing, then they receive an email confirmation that includes the information included in the beta on-page confirmation alert.  
- [x] Given a user is on sign and submit in the production environment, when they submit their filing, then they receive an email confirmation that includes the information included in the production on-page confirmation alert.  

### Identify details of email message
- Who sends: noreply@cfpb
- Subject: [BETA]......  
- Who receives the alert? Which contacts are main line vs. CC. The main submitter, associated accounts, primary contact
- Primarily select initial submitter and then request who else received the alert via forwarding
- Body: Basic email text 

### Tasks
Team members should create tasks and add links (below) prior to sprint planning.

#### UX
- [x] Write initial user story
  - Review against task analysis for accuracy and relevance
  - Add a link to the story from the task analysis
- [x] Validate user story with the team
  - Review for specificity and completeness

#### Content
- [x] https://github.com/cfpb/sbl-ux/issues/23

#### Back end
- [x] https://github.com/cfpb/regtech-mail-api/issues/45
- [x] https://github.com/cfpb/regtech-mail-api/issues/52
- [x] https://github.com/cfpb/sbl-filing-api/issues/495
- [x] https://github.com/cfpb/regtech-mail-api/issues/59

**Comment by lchen-2101** [comment]
title:
HMDA filing accepted!

body:
HMDA filing accepted!
Congratulations, you have successfully completed your HMDA filing for 2022!
Your data and signature were received and recorded on {timestamp}. Your receipt number for this submission is {lei-year-quarter-timestamp}

**Comment by natalia-fitzgerald** [comment]
The following reflects what we implemented on beta (and what we plan to implement on production when the time comes): 

### Beta implementation: Alert and Email
| Alert | Email |  
|------------| ------------|
|![Frame 1529](https://github.com/user-attachments/assets/2b1e15e2-6b80-42bf-8ec0-d3aef38ffa53)|<img width="576" alt="Screenshot 2024-12-05 at 11 44 04 AM" src="https://github.com/user-attachments/assets/5a7a8916-7c06-42e8-b468-5aa028e59799">|

### Production implementation: Alert and Email
| Alert | Email |  
|------------| ------------|
|![Notification (Success)](https://github.com/user-attachments/assets/c6809779-b618-4f8b-8a18-d985de648b27)|<img width="577" alt="Screenshot 2024-12-05 at 11 44 10 AM" src="https://github.com/user-attachments/assets/02929c90-d9d5-4647-8077-fae55e5d69dd">|

**Comment by angelcardoz** [comment]
This is the language we need in the beta email confirmation. 
**Beta release:** 

Subject: [BETA] Small Business Lending Data Filing Confirmation 
Congratulations! This email confirms that Test Boss submitted a filing on Dec. 11, 2024 at 3:32 p.m. EST. The confirmation number for this filing is 177300BP2N2ZZQFLQI90-2024-7-1733949170.
 
The beta platform is for testing purposes only and user-supplied data may be removed at any time. Email our support staff at sblhelp@cfpb.gov to share feedback or return to the platform to upload a new file and continue testing.

**Comment by angelcardoz** [comment]
This is the draft email for production.  

**Production release:**
 
Subject: Small Business Lending Data Filing Confirmation 
Congratulations! This email confirms that Test Boss submitted a filing on Dec. 11, 2024 at 3:32 p.m. EST. The confirmation number for this filing is 177300BP2N2ZZQFLQI90-2024-7-1733949170.
 
If you have any questions or need additional support, email our support staff at sblhelp@cfpb.gov.
