### ISSUE TITLE
[Story] Review filing information

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-project#258]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [[Epic] Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story

-  As a filer, I want to determine whether my filing information is accurate and complete, so that I can either update my information or proceed to the next section.

### Acceptance criteria

- Given a user has completed all previous steps, when they reach sign and submit and the system displays their filing information, then they will be able to review the information to determine whether it is accurate and complete.

### Tasks

Team members should create tasks and add links (below) prior to sprint planning.

#### UX
- [x] Write initial user story and map it to task analysis
- [x] Validate user story 
  - Review against task analysis for accuracy and relevance
  - Review for specificity and completeness
- [x] https://github.com/cfpb/sbl-ux/issues/15

#### Content
- Add task

#### Front end
- Add task

#### Back end
- Add task

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
This story has been implemented as a feature and is now live on beta. This story is completed and can be closed.
