### ISSUE TITLE
[Story] Know where to update or verify inaccurate or incomplete filing information

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-project#259]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [[Epic] Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story

- As a filer, I want to know where to go to update or further verify information I find in my review, so that I can file with accurate and complete information.

### Acceptance criteria

- Given a user is on the sign and submit page, when they navigate to each section the system will display instructions on where a user must go to update inaccurate or incomplete information they find in their review, then they will be able to follow the instructions and make the necessary changes.

### Tasks

Team members should create tasks and add links (below) prior to sprint planning.

#### UX
- [x] Write initial user story and map it to task analysis
- [x] Validate user story 
  - Review against task analysis for accuracy and relevance
  - Review for specificity and completeness
- [x] Map out where a filer must go to change inaccurate or incomplete information
- [x] https://github.com/cfpb/sbl-ux/issues/15

#### Content
- [ ] Task (link)

#### Front end
- [ ] Task (link)

#### Back end
- [ ] Task (link)

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @dan-padgett 
For the purposes of the current work we're doing to enable sign and submit, does this content work: 
<img width="512" alt="Screenshot 2024-10-21 at 11 11 00 AM" src="https://github.com/user-attachments/assets/929a6ed1-6c56-46e1-8435-98f5fbc0311a">

**Comment by dan-padgett** [comment]
@natalia-fitzgerald Yes, I think that content meets the intent of what we're aiming for currently.

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
This feature is now live on beta. This story is completed and can be closed.
