### ISSUE TITLE
[Story]  Confirm accurate and complete filing information 

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-project#260]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [[Epic] Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story

- As a filer, I want a way to confirm that I've reviewed each section and determined the information displayed is correct, so that I can ensure the information I'm submitting is accurate and complete.

### Acceptance criteria

- Given a user has reviewed the information in each section and determined that the information is correct, when they check the checkbox, then the checkbox will display a visual cue (e.g. checkmark) indicating that the user has reviewed the section and confirmed that the information is accurate and complete.

### Tasks

Team members should create tasks and add links (below) prior to sprint planning.

#### UX
- [x] Write initial user story
- [x] Map story issue to the task analysis
- [x] Validate user story
  - Review against task analysis for accuracy and relevance
  - Review for specificity and completeness
- [x] https://github.com/cfpb/sbl-ux/issues/9
- [x] https://github.com/cfpb/sbl-ux/issues/15

#### Content
- [x] Write content (label and helper text)

#### Front end
- Add task

#### Back end
- Add task

#### Data
- Add task

**Comment by natalia-fitzgerald** [comment]
| Voluntary reporter | Not voluntary reporter |
|------------|------------|
|<img width="494" alt="Screenshot 2024-09-30 at 11 58 31 AM" src="https://github.com/user-attachments/assets/1b1654e6-00fe-443f-8d85-bad9d878aa9b">|<img width="468" alt="Screenshot 2024-09-30 at 11 58 36 AM" src="https://github.com/user-attachments/assets/929a4cb8-c895-40e1-b1d2-26bc48af0984">|
