### ISSUE TITLE
[Epic] View filing

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#326]
**Milestone:** [Link to milestone]
Add a few sentences to describe the milestone.

# Epic: View filing

### Overview

- The purse of this epic is to facilitate a user-friendly process for users to view their submissions post-filing.
-  This epic becomes relevant once a user has submitted a filing and subsequently needs to view, verify, or use the information for further processing. 
- This epic includes features for knowing when a filing is complete, accessing the completed filing, viewing the completed filing, printing a summary of the completed filing, and re-sending a filing confirmation email.  

### Tasks

Use the following checklist to ensure each epic is built out properly. If needed, you can add or remove items.
- [ ] Pull together initial list of relevant user stories for this epic
- [ ] Make a list of the content requirements for this epic
- [ ] Make a list of the technical requirements for this epic
- [ ] Post current wireframes and mock-ups
- [ ] Review wireframes and mock-ups with FEWD, BEWD, Data, SBL Help, Content team members
- [ ] Refine user stories to prepare for development phase
- [ ] Identify and capture tasks for user testing
- [ ] Conduct user testing

### MVP (Beta release)
- [ ] https://github.com/cfpb/sbl-project/issues/307
- [ ] https://github.com/cfpb/sbl-project/issues/308
- [ ] https://github.com/cfpb/sbl-project/issues/309
- [ ] https://github.com/cfpb/sbl-project/issues/310
- [ ] https://github.com/cfpb/sbl-project/issues/311
- [ ] https://github.com/cfpb/sbl-project/issues/315

### Backlog (post-MVP)
- Story (link)

### Technical
- List item
- List item

### Content
- Link item
- Link item

### Research goals
- Add here

### Task ideation
- Add here

#### Updated: MM/DD/YYYY

| Page name | Page name | Page name |
|------------|------------|------------|
|![Image](Link)|![Image](Link)|![Image](Link)|
