### ISSUE TITLE
[Epic] Upload file

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/sbl-project#35]
#### Milestone: [Upload and validate file](https://github.com/cfpb/sbl-project/milestone/4)
The shared data filing platform will be used by filers of small business lending (SBL) and mortgage lending (HMDA) data to centrally manage their account (user profile, financial institution details, login through Login,gov, etc.). .

# Epic: Upload file
### Overview 
- User can upload a .csv of their small business lending data applicafion register.
  - If the selected file does not meet platform specifications, the file will be prevented from uploading and errors will be listed.
  - Indication that upload is successful and complete
  - Summary of successful upload
- Once upload is successful validation checks run
  - Indication that validations check is completed. 
  - High-level validation summary (Error and Warnings count)
- Button to proceed to the next step: Resolve errors. 
- Once initial file has been uploaded a link will appear to upload a new file (which replaces the previous submission)
  - Indication that selecting and uploading a new file will replace the previous submission.

### Tasks
- [ ] Pull together the relevant user stories for this epic
- [ ] Make a list of the content requirements for this epic
- [ ] Make a list of the technical requirements for this epic
- [ ] Document the work that we have done up until now including images and discussion
- [ ] Post current wireframes and mock-ups
- [ ] Review wireframes and mock-ups with FEWD, BEWD, Data, SBL Help, Content team members
- [ ] Refine user stories to prepare for development phase
- [x] Identify tasks for user testing (to validate findability of information, clarity of content and layout, users able to successfully complete important tasks)

### MVP (Beta release)
- [ ] https://github.com/cfpb/sbl-project/issues/103
- [ ] https://github.com/cfpb/sbl-project/issues/179
- [ ] https://github.com/cfpb/sbl-project/issues/160
- [ ] https://github.com/cfpb/sbl-project/issues/104
- [ ] https://github.com/cfpb/sbl-project/issues/159
- [ ] https://github.com/cfpb/sbl-project/issues/158
- [ ] https://github.com/cfpb/sbl-project/issues/161

### Backlog (post-MVP)
- [ ] https://github.com/cfpb/sbl-project/issues/109
- As a filer, I want details describing why my file failed to upload, so I have a better understanding of the issue and I can take steps to fix my file.

### Technical
- List item
- List item

### Content
- Intro content explaining what happens in this step (upload and validations check)
- Content for replacing a previous submission with a new submission
- File specifications

### Research goals
- When a file has already been uploaded, determine whether users expect the ability to upload a new file to appear above or below the file summary.
- Understand what users expect to happen when they replace a file
- Learn what users expect from the upload process, including what information they see after a successful upload

### Task ideation
- Determine whether a file has already been uploaded
- Upload a new file
- Identify next steps when there's a problem with an upload

#### Updated: MM/DD/YYYY

| Page name | Page name | Page name |
|------------|------------|------------|
|![Image](Link)|![Image](Link)|![Image](Link)|

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @sthomas93 
Can we remove the following stories from this epic (specifically the list here: https://github.com/cfpb/sbl-project/issues/35#issue-1902146267)

- #105 (Closed)
- #111 (Move to Resolve errors epic)
- #108 (Move to Resolve errors epic)
- #107 (move to filing home - post-MVP)
- #110 (move to global issue)

**Comment by angelcardoz** [comment]
@natalia-fitzgerald, I'm still reviewing the task analysis and creating new stories. I plan on updating this epic very soon.
