### ISSUE TITLE
[Story] Get help associating email domain with financial institution

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-project#62]
### User story

As a filer, I would like to get help associating my email domain with the financial institution I am authorized to file for, so that I can complete my user profile and access the filing platform.

### Acceptance criteria

- Given a user's financial institution email address does not match any of our approved email domains and their institution has an LEI, when the user logs in through Login.gov, then they will be redirected to the **Update your user profile** (Salesforce form) and will be asked to submit their selection to the support staff for processing. 

### Depends on
- #12

#### Front end
- [x] [[Page][Salesforce] Complete Your User Profile](https://github.com/cfpb/sbl-frontend/issues/220)
- [x] [[Component] Add Financial Institution button](https://github.com/cfpb/sbl-frontend/issues/221)
- [x] [Design Review Update - Complete Your User Profile (No Assocations)](https://github.com/cfpb/sbl-frontend/issues/310)

#### Back end
- [ ] Add here
- [ ] Add here

### Context
[Add any helpful context here]
