### ISSUE TITLE
Seed mock data, and how to create mock institutions for front end testing

### ISSUE THREAD

**Issue by lchen-2101** [cfpb/sbl-project#66]
## Context

While the API and the data models are updated; without data, it would be difficult for front end to test integration

### Pre-requisites

refer to https://github.com/cfpb/sbl-project/blob/main/LOCAL_DEV_COMPOSE.md to run the local supporting services.

## Task

- [x] sql script to populate lookup tables, so institutions api can be called to create institutions (this won't be necessary once https://github.com/cfpb/regtech-user-fi-management/issues/61 is completed)
- [ ] steps to create an institution
- [ ] steps to associate domains with institution
