### ISSUE TITLE
[Epic] Getting started shared landing page (unauthenticated) 

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-project#7]
#### Milestone: Authenticate
The shared data filing platform will be used by filers of small business lending (SBL) and mortgage lending (HMDA) data to centrally manage their account (user profile, financial institution details, login through Login,gov, etc.). 

## Epic: Getting started shared landing (unauthenticated)
The shared data filing platform landing page will be the first place a user lands before they have logged in to use the filing platform. Once the filer is logged in and have successfully completed their user profile they will be directed to the SBL or HMDA filing apps to file their data.

### MVP (release date: 12/31/2024)
- [x] https://github.com/cfpb/sbl-project/issues/257
- [ ] https://github.com/cfpb/sbl-project/issues/262
- [x] https://github.com/cfpb/sbl-project/issues/273

### Backlog (write user story issues)
- Add email signup
- Add CFPB megamenu

### Open beta (released: 8/1/2024)
- [x] https://github.com/cfpb/sbl-project/issues/3
- [x] https://github.com/cfpb/sbl-project/issues/4
- [x] https://github.com/cfpb/sbl-project/issues/29
- [x] https://github.com/cfpb/sbl-project/issues/98

## Tasks
- [X] Make a list of the relevant user stories for this page
- [X] Make a list of the required content for this page
- [x] Document the work that we have done up until now including images and discussion
- [x] Surface any open questions
- [x] Explore ways to bring more prominence to the fact that a user must sign in using their financial institution email address.
- [x] Mock-up the steps a user must take to start using the filing platform? 
    - Register for an LEI with GLEIF
    - Create a Login.gov account
    - Sign in to Login.gov with your financial institution email address
    - Complete user profile 
- [x] Identify tasks for user testing (to validate findability of information, clarity of content and layout, users able to successfully complete important tasks)
- [x] Reviewed by team for input & feedback
- [x] User testing conducted

## Technical requirements
- When a user clicks on "Sign in with Login.gov", then should be routed to the login.gov log in flow
- Late pre-MVP / post-MVP: add a "megamenu" to the top of this page that stays in sync with cf.gov without undue maintenance ([see options](https://github.com/cfpb/sbl-project/issues/7#issuecomment-1847445137))

## Content requirements
- Orient the user to the fact that they are on a shared filing platform for lending data (e.g. SBL, HMDA, NBR).
- Inform the user of what is needed to create an account (LEI), log in to the filing platform (Login.gov account), and begin the filing process.
- Information on Login.gov and why we use it (keep information safe and secure).
- Inform the user that in order to access the filing platform they will need to create a Login.gov account that is tied to their FI email address (not a personal email address).
- Inform the user that they must log in to Login.gov using their financial institution email address. 
- Inform the user of what they should do if they need help (they can go to the FAQ page or they can submit a question to SBL help via the help form).
- Inform the user of the requirements for logging in and creating an account.
- Privacy Act Notice, Paperwork Reduction Act, CFPB Notice and Consent 

### Task ideation
Draft list of items to account for in user testing.
- Is this page easy to find on the cfpb public-facing website?
- Looking at this page, can you tell me what this page is for? (can they identify this as a starting point for SBL & HMDA)
- What stands out on this page?
- Is the information here clear and easy to understand? 
    - based on the information provided, do you feel like you would be well prepared to get started?
- If you needed help, how would you be able to get the support you needed?
    - what do you expect the process would be to get your questions answered?
- Is there anything missing from this page that you would expect to see?
- Supposing you met the criteria and your FI has an LEI, what would you do next?
    - what do you expect would happen when you try to do that?
    - (if answer is login.gov) go ahead and select "create an account"

### Updated 12/12/2023

| Shared landing page (unauthenticated)|
|------------|
|![MVP_ Shared platform (unauthenticated)](https://github.com/cfpb/sbl-project/assets/77348967/0af5fcff-8aac-4ee3-8b60-fbb63de38a3e)|

| Privacy Act Notice | Paperwork Reduction Act |
|------------|------------|
|![MVP_ Privacy Act Notice (separate page)](https://github.com/cfpb/sbl-project/assets/77348967/35e557c8-3d7e-4922-971d-70675800ed85)|![MVP_ Paperwork Reduction Act (separate page)](https://github.com/cfpb/sbl-project/assets/77348967/5dd64cf0-f047-4c43-a866-fd84d0e2ddb1)|

**Comment by angelcardoz** [comment]
@dan-padgett, can we check off "User testing conducted" under tasks?

**Comment by dan-padgett** [comment]
@angelcardoz Yes, the only thing we haven't tested is the first question: "Is this page easy to find on the cfpb public-facing website?" But since we're providing a direct link for MVP, that's something we can test a little later on.

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
I am not closing this epic because I see some backlog items. We need to write user stories for these and then we'll need to decide where they should live. 

Backlog (write user story issues)
- Add email signup
- Add CFPB megamenu
- Link from Small business lending database page to this page
- Implement responsive design (mobile)
