### ISSUE TITLE
[Epic] Filing home shared landing page (authenticated)

### ISSUE THREAD

**Issue by kristenshaw4** [cfpb/sbl-project#8]
#### Milestone: [Authorization](https://github.com/cfpb/sbl-project/milestone/3)
The shared data filing platform will be used by filers of small business lending (SBL) and mortgage lending (HMDA) data to centrally manage their account (user profile, financial institution details, login through Login,gov, etc.). 

# Epic: Filing home shared landing page (authenticated)
- A user will land on the shared data filing platform landing page (authenticated) after they have signed in with Login.gov and completed their platform user profile, successfully associating with one or more financial institutions (either selected from the pre-populated list of financial institutions that match their email domain or self-selected by filling out and submitting the form to our support staff).
- The CFPB shared data filing platform landing page (authenticated) will be the central place where an authenticated user can access the ~HMDA or~ SBL filing platforms, request changes to their shared user profile, view their financial institution details, and read relevant content. 

### Tasks
- [X] Make a list of the relevant user stories for this page
- [X] Make a list of the required content for this page
- [x] Document the work that we have done up until now including images and discussion
- [x] Define tasks for user testing (to validate findability of information, clarity of content and layout, users able to successfully complete important tasks)

### MVP (Beta release)
- [x] https://github.com/cfpb/sbl-project/issues/76
- [x] https://github.com/cfpb/sbl-project/issues/77
- [x] https://github.com/cfpb/sbl-project/issues/78
- [x] https://github.com/cfpb/sbl-project/issues/79
- [x] https://github.com/cfpb/sbl-project/issues/80

### Backlog
- [ ] As a filer who submits both SBL and other data to CFPB (e.g. HMDA or NBR), I would like my financial institution details to be centrally managed, so that I don’t have to maintain the same information in multiple places. 
- [ ] As a filer  who submits both SBL and other data to CFPB (e.g. HMDA or NBR), I want to be able to have a single user profile that is shared among the CFPB platforms, so that I don’t have to maintain the same information in multiple places.
- [ ] As a filer, I want to view pending associated financial institutions, so I know I've submitted a request to associate a specific financial institution with my profile. 
- [ ] User can see notifications for actions they need to take.
- [ ] Navigate to "File for HMDA"
- [ ] Notification that a user has successfully completed their user profile (appears on first visit)

## Technical requirements
- User management API
  - Reads data from and writes data back to Keycloak
- Institutions API
  - Retrieve institution data by LEI and email domain

## Content requirements
Overview of what a user can do:
- Button: "File your small business lending data"
- Link: "Update your user profile" 
- Link: "View your financial institution profile"
- Link: Logout (logs the user out of Keycloak specifically)
- Link: First name and last name (opens View your user profile)
- Link: Financial institution name + LEI (opens View your financial institution profile)

### Task ideation)
**Draft list of items to account for in user testing**
- Is this what you expected to see following the user profile page?
- What stands out to you?
- What do you think you can do here?
- What information would you expect to see that isn't represented?
- If you needed to update your name or email address, how would you do that?
- If you needed to change the FIs you are able to file for, how would you do that?
- If you were ready to start filing your SBL data, what would you do to get started?

### Updated 2/16/2024
| Shared platform (authenticated) | 
|------------|
|![Group 379](https://github.com/cfpb/sbl-project/assets/77348967/ba91612d-b4a4-4ac2-9fac-b69486e81885)|

**Comment by natalia-fitzgerald** [comment]
@sthomas93 @angelcardoz 
I updated the mock-ups and some of the epic details based on the latest.

**Comment by angelcardoz** [comment]
@dan-padgett, can we check off "Define tasks for user testing (to validate findability of information, clarity of content and layout, users able to successfully complete important tasks)" under tasks?

**Comment by dan-padgett** [comment]
@angelcardoz Yes, the tasks there look good for testing. Some of them were addressed during the February focus group. A few others would best be investigated in a usability test--but they have been defined per the checklist.
