### ISSUE TITLE
[Epic] Login.gov account creation and sign in

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-project#9]
#### Milestone: Authentication
The shared data filing platform will be used by filers of small business lending (SBL) and mortgage lending (HMDA) data to centrally manage their account (user profile, financial institution details, login through Login,gov, etc.). 

# Epic: Login.gov account creation and sign in
The fist step in accessing the shared data filing platform will be to create an account and sign in with Login.gov. A user must sign in with their financial institution email address. Once the filer is signed in and has completed their user profile they will be directed to the SBL or HMDA filing apps to file their data.

### Tasks
- [X] Make a list of the relevant user stories for this page
- [X] Document images of the Login.gov account creation and sign in
- [x] Identify UI/UX tasks related to setting up the platform to use Login.gov
- [x] Determine what is customizable within Login.gov (content, imagery) https://developers.login.gov/design-guidelines/
- [x] Determine what customization we would like to add
- [x] Update mock-ups to reflect this customization
- [x] Identify tasks for user testing (to validate the process works as expected, clarity of pre-login content to set users up for success, users able to successfully complete important tasks)
- [x] Reviewed by team for input & feedback
- [x] User testing conducted (limited ability to make changes, but let's validate the process works as we expect)

## Decisions
The following list reflects the output of team discussions and decisions:
- Users of the CFPB shared data filing platform must sign in to Login.gov with their financial institution email address and not a personal email address.  
- If a user signs in with a personal email address (that is on our list of personal email domains) it will trigger an alert stating that personal email domains are not supported
  - Build an explicit deny list of personal email domains (gmail.com, yahoo.com, hotmail.com, etc.) to tell users up-front that we don't support non-financial institution email addresses
  - In this scenario if the email domain is in our deny list they would reach a page with an alert asking the user to go back to Login.gov and login with their financial institution email address.
- The user profile email address will auto-populate within our system and is pulled in from the address the user used to sign in to Login.gov.
   - We are able to setup Keycloak so that whenever the user logs in, it will always be sync'ed with the email the user used to sign in to Login.gov.

## User stories
- [x] https://github.com/cfpb/sbl-project/issues/64
- [x] https://github.com/cfpb/sbl-project/issues/65
- [x] https://github.com/cfpb/sbl-project/issues/74
- [x]  https://github.com/cfpb/sbl-project/issues/75
- Check to make sure login.gov friendly account name is "Small Business Lending Data Submission Platform"

## Technical requirements
- User management API
  - Reads data from and writes data back to Keycloak

## Content requirements
- [ ] Add here

### Task ideation 
- *Login.gov landing page* Is this what you expected to see? (Is it clear that this is a service that enables cfpb to provide secure sign in?)

## Current designs (MVP)
Updated: 2/16/2024

### Sign in with Login.gov 
When the user clicks "Sign in with Login.gov" they will be directed to the Login.gov landing page. There they will enter their email address and password and click the sign in button. This will take them to the CFPB shared platform home (authenticated) page. 

| CFPB shared platform (unauthenticated) | Login.gov landing page | 
|------------|------------|
|![10](https://github.com/cfpb/sbl-project/assets/77348967/3bb9c95d-2664-4b24-bb6c-c68142a00e65)|![11](https://github.com/cfpb/sbl-project/assets/77348967/9b0f80ed-c3ce-42d8-a224-4cc045d4144c)|

### Create an account with Login.gov 
When the user clicks "Create an account with Login.gov" they will be directed to the Login.gov landing page. The account creation process is 7 screens and includes email confirmation, creating a password, setting up an authentication method, adding an authentication app, and continuing to the CFPB website. 

| CFPB shared platform (unauthenticated) | Login.gov landing page | 
|------------|------------|
|![Group 27](https://github.com/cfpb/sbl-project/assets/77348967/ab6010da-0a4e-424e-86ea-fd5c88a89db5)|![Screen Shot 2023-07-07 at 2 06 44 PM](https://github.com/cfpb/sbl-project/assets/77348967/0d3540b0-a581-4f71-aa3f-67e7ba9fcf8d)

#### Login.gov screens
1. Sign in / Create an account 
2. Create your account 
3. Confirm your email 
4. Create a strong password
5. Authentication method setup 
6. Add an authentication app
7. You've added your first authentication method
8. Continue to the CFPB

| 1. Sign in / Create an account | 2. Create your account | 
|------------|------------|
|![1](https://github.com/cfpb/sbl-project/assets/77348967/dcabae06-6ec0-4a44-94c5-a9589a15c736)|![2](https://github.com/cfpb/sbl-project/assets/77348967/bc75f0a2-c752-469a-b231-71302633c102)|

| 3. Confirm your email | 4. Create a strong password | 
|------------|------------|
|![3](https://github.com/cfpb/sbl-project/assets/77348967/b28a0a1d-3119-4082-b5bf-1e3347695dd6)|![4](https://github.com/cfpb/sbl-project/assets/77348967/a2cdb26a-e297-4654-988f-89ca258d36ff)|

| 5. Authentication method setup | 6. Add an authentication app | 
|------------|------------|
|![5](https://github.com/cfpb/sbl-project/assets/77348967/65768d20-6e7d-4b6d-bd20-159c7dcd201c)|![6](https://github.com/cfpb/sbl-project/assets/77348967/514fbe00-3efd-4422-8470-de3c42c5f38d)|

| 7. You've added your first authentication method | 8. Continue to the CFPB | 
|------------|------------|
|![7](https://github.com/cfpb/sbl-project/assets/77348967/828e81b4-2c9e-45b2-9a18-77348d40e994)|![8](https://github.com/cfpb/sbl-project/assets/77348967/7982f5e0-df78-444d-8ce4-7fb9f1332363)|

### Your account
A user's email address will auto populate within the CFPB shared filing platform in the "Complete your user profile" page and the "Request changes to your user profile" pages. If a user wishes to make a change to the email address they use to sign in to Login.gov or add a new email address they will do so within Login.gov at https://secure.login.gov/account. Changes to email addresses will be handled in Login.gov and not in the CFPB shared filing platform.

| Your account |
|------------|
![Frame 1](https://github.com/cfpb/sbl-project/assets/77348967/da4c55a7-35f0-42a8-bcd9-67d71dce6fa5)

**Comment by dan-padgett** [comment]
@angelcardoz checking off the user testing item here since we covered this step of the process during the focus group
